# Generated by Django 4.0 on 2022-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(help_text='PATH')),
                ('method', models.CharField(help_text='METHOD', max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='You must enter email field', max_length=254, verbose_name='email_adress'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(help_text='Here you must enter surname', max_length=120, verbose_name='family_name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='Here you must enter name', max_length=120, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
